---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-alert-mysql-pvc
  namespace: monitoring
spec:
  storageClassName: csi-alicloud-disk-efficiency
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-alert-mysql
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: mycnf
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: prometheus-alert-mysql-pvc
        - name: mycnf
          configMap:
            name: mycnf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: monitoring
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: v1
data:
  my.cnf: |
    [mysqld]
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql

    character_set_server=utf8mb4

    # Custom config should go here
    !includedir /etc/mysql/conf.d/
    !includedir /etc/mysql/mysql.conf.d/
kind: ConfigMap
metadata:
  name: mycnf
  namespace: monitoring
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-alert-mysql
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 120.237.78.114/32
spec:
  ingressClassName: nginx
  rules:
  - host: alertdb.sjfood.us
    http:
      paths:
      - backend:
          service:
            name: mysql
            port:
              number: 3306
        path: /
        pathType: Prefix
  tls:
  - hosts:
      - alertdb.sjfood.us
    secretName: sjfood-us-tls