apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-gateway
  labels:
    helm.sh/chart: loki-simple-scalable-1.8.11
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: k8sgpt
    app.kubernetes.io/version: "2.6.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
data:
  nginx.conf: |
    worker_processes  5;  ## Default: 1
    error_log  /dev/stderr;
    pid        /tmp/nginx.pid;
    worker_rlimit_nofile 8192;

    events {
      worker_connections  4096;  ## Default: 1024
    }

    http {
      client_body_temp_path /tmp/client_temp;
      proxy_temp_path       /tmp/proxy_temp_path;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;

      proxy_http_version    1.1;

      default_type application/octet-stream;
      log_format   main '$remote_addr - $remote_user [$time_local]  $status '
            '"$request" $body_bytes_sent "$http_referer" '
            '"$http_user_agent" "$http_x_forwarded_for"';
      access_log   /dev/stderr  main;

      sendfile     on;
      tcp_nopush   on;
      resolver kube-dns.kube-system.svc.cluster.local;

      client_max_body_size 100M;

      server {
        listen             8080;

        location = / {
          return 200 'OK';
          auth_basic off;
        }

        location = /api/prom/push {
          proxy_pass       http://loki-write.monitoring.svc.cluster.local:3100$request_uri;
        }

        location = /api/prom/tail {
          proxy_pass       http://loki-read.monitoring.svc.cluster.local:3100$request_uri;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }

        location ~ /api/prom/.* {
          proxy_pass       http://loki-read.monitoring.svc.cluster.local:3100$request_uri;
        }

        location ~ /prometheus/api/v1/alerts.* {
          proxy_pass       http://loki-read.monitoring.svc.cluster.local:3100$request_uri;
        }

        location ~ /prometheus/api/v1/rules.* {
          proxy_pass       http://loki-read.monitoring.svc.cluster.local:3100$request_uri;
        }

        location = /loki/api/v1/push {
          proxy_pass       http://loki-write.monitoring.svc.cluster.local:3100$request_uri;
        }

        location = /loki/api/v1/tail {
          proxy_pass       http://loki-read.monitoring.svc.cluster.local:3100$request_uri;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }

        location ~ /loki/api/.* {
          proxy_pass       http://loki-read.monitoring.svc.cluster.local:3100$request_uri;
        }

        location ~ /compactor/.* {
          proxy_pass       http://loki-read.monitoring.svc.cluster.local:3100$request_uri;
        }

        location ~ /distributor/.* {
          proxy_pass       http://loki-write.monitoring.svc.cluster.local:3100$request_uri;
        }

        location ~ /ring {
          proxy_pass       http://loki-write.monitoring.svc.cluster.local:3100$request_uri;
        }

        location ~ /ingester/.* {
          proxy_pass       http://loki-write.monitoring.svc.cluster.local:3100$request_uri;
        }

        location ~ /ruler/.* {
          proxy_pass       http://loki-read.monitoring.svc.cluster.local:3100$request_uri;
        }

        location ~ /scheduler/.* {
          proxy_pass       http://loki-read.monitoring.svc.cluster.local:3100$request_uri;
        }

        client_max_body_size 100M;
      }
    }