apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loki-read
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: read
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: read
  maxUnavailable: 1