apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki-write
  labels:
    helm.sh/chart: loki-simple-scalable-1.8.11
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: k8sgpt
    app.kubernetes.io/version: "2.6.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: write
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: k8sgpt
      app.kubernetes.io/component: write
    matchExpressions:
      - key: prometheus.io/service-monitor
        operator: NotIn
        values:
          - "false"
  endpoints:
    - port: http-metrics
      relabelings:
        - sourceLabels: [job]
          replacement: "default/loki-write"
          targetLabel: job
        - replacement: "k8sgpt-loki"
          targetLabel: cluster
      scheme: http