apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
  name: main
  namespace: monitoring
spec:
  image: quay.io/prometheus/alertmanager:v0.25.0
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: alert-router
      app.kubernetes.io/instance: main
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: kube-prometheus
  # 副本数改为 1
  replicas: 1
  # 数据保留时间
  retention: 120h
  # 指定secretName
  configSecret: alertmanager-main
  # 扩展的URL，防止告警时生成的URL为容器ID
  externalUrl: https://alertmanager.k8s.local
  # 持久化数据, 防止容器重启导致silence规则丢失
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: nfs  # 填写你的 SC
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  resources:
    limits:
      cpu: 50m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 100Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
