apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-alert-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi