apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promealert-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi