apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promealert-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: alicloud-disk-efficiency
  resources:
    requests:
      storage: 20Gi