apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  generation: 1
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-event-rules
  namespace: monitoring
spec:
  groups:
  - name: aliyun-prom-event
    rules:
    - alert: EventOOMKilled
      annotations:
        eventurl: https://arms.console.aliyun.com/#/tracing/event/cn-hangzhou
        message: OOMKilled events occurred in {{ $labels.namespace }}.{{ $labels.pod_name
          }}.
      expr: |
        sum( rate(aliyun_k8s_event{reason="OOMKilled"}[1m])*60) by (namespace,pod_name) >0
      for: 5m
      labels:
        severity: critical
    - alert: EventScaling
      annotations:
        eventurl: https://arms.console.aliyun.com/#/tracing/event/cn-hangzhou
        message: EventScaling events occurred in {{ $labels.namespace }}.{{ $labels.pod_name
          }}.
      expr: |
        sum( rate(aliyun_k8s_event{reason="ScalingReplicaSet"}[1m])*60) by (namespace,pod_name) >0
      for: 5m
      labels:
        severity: critical