apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-rds
  namespace: monitoring
  labels:
    app: postgres
    app.kubernetes.io/name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      app.kubernetes.io/name: postgresql
  template:
    metadata:
      labels:
        app: postgres
        app.kubernetes.io/name: postgresql
    spec:
      containers:
      - name: teamcityop
        image: ccr.ccs.tencentyun.com/rig-agent/postgres-exporter:v0.8.0
        args:
          - "--web.listen-address=:9187"
          - "--log.level=info"
        env:
          - name: DATA_SOURCE_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: username
          - name: DATA_SOURCE_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
          - name: DATA_SOURCE_URI
            value: "xxxxxxxxx.pg.rds.aliyuncs.com:1433/postgres?sslmode=disable"
        ports:
        - name: http-metrics
          containerPort: 9187
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: monitoring
type: Opaque
stringData:
  username: export
  password: xxxxxxxxx #对应 PostgreSQL 密码
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: postgres-exporter
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 9187
      targetPort: 9187