apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  generation: 1
  labels:
    role: alert-rules
  name: kubernetes-event-rules
  namespace: vm-operator
spec:
  groups:
  - name: k8s-prom-event
    rules:
    - alert: EventOOMKilled
      annotations:
        eventurl: https://arms.console.aliyun.com/#/tracing/event/cn-hangzhou
        description: OOMKilled events occurred in {{ $labels.namespace }}.{{ $labels.pod_name
          }}.
      expr: |
        sum(rate(aliyun_k8s_event{reason="OOMKilled"}[1m])*60) by (namespace,pod_name) >0
      for: 5m
      labels:
        severity: critical
    - alert: EventScaling
      annotations:
        eventurl: https://arms.console.aliyun.com/#/tracing/event/cn-hangzhou
        description: EventScaling events occurred in {{ $labels.namespace }}.{{ $labels.pod_name
          }}.
      expr: |
        sum( rate(aliyun_k8s_event{reason="ScalingReplicaSet"}[1m])*60) by (namespace,pod_name) >0
      for: 5m
      labels:
        severity: critical