apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: http-discover
  namespace: monitoring
spec:
  jobName: ingress-discover # 任务名称
  prober: # 指定blackbox的地址
    url: blackbox-exporter.monitoring.svc:19115
  module: http_2xx # 配置文件中的检测模块
  targets: # 目标（可以是static配置也可以是ingress配置）
    ingress:
      namespaceSelector:
        any: true
      relabelingConfigs:
      - sourceLabels: [__meta_kubernetes_ingress_annotation_prometheus_io_probe]
        action: keep # 保留具有 prometheus.io/scrape=true 这个注解的Service
        regex: "true"
      - action: replace
        sourceLabels: [__meta_kubernetes_ingress_scheme, __meta_kubernetes_ingress_host,__meta_kubernetes_ingress_path]
        separator: ;
        targetLabel: __param_target
        regex: (.+);(.+);(.+)
        replacement: ${1}://${2}${3}
      - sourceLabels: [__meta_kubernetes_namespace]
        targetLabel: namespace
      - sourceLabels: [__meta_kubernetes_ingress_name]
        targetLabel: ingress
  interval: 20s