---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster
  namespace: vm-operator
spec:
  # 数据保留时间 h/d/w/y
  retentionPeriod: "1w"
  # 复制因子定义了在不同存储节点之间复制数据的副本数量。
  replicationFactor: 1
  # 用于运行VMSelect、VMStorage和VMInsert Pods的ServiceAccount的名称。"
  serviceAccountName: vm-operator
  vmstorage:
    logFormat: json
    replicaCount: 2
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
              - "vmstorage"
          topologyKey: "kubernetes.io/hostname"
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 2Gi
          storageClassName: nfs-csi-stateful
    storageDataPath: "/vm-data"
    # serviceSpec:
    #   metadata:
    #     name: vmstorage-node-access
    #     labels:
    #       app.kubernetes.io/name: vmstorage
    #   spec:
    #     type: NodePort
    resources:
      limits:
        cpu: "1"
        memory: 1500Mi
  vmselect:
    replicaCount: 2
    cacheMountPath: "/cache"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
              - "vmselect"
          topologyKey: "kubernetes.io/hostname"
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 2Gi
          storageClassName: nfs-csi-stateful
    # serviceSpec:
    #   metadata:
    #     name: vmselect-access
    #     labels:
    #       app.kubernetes.io/name: vmselect
    #   spec:
    #     type: ClusterIP
    resources:
      limits:
        cpu: "1"
        memory: "1000Mi"
      requests:
        cpu: "0.5"
        memory: "500Mi"
  vminsert:
    replicaCount: 2
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
              - "vminsert"
          topologyKey: "kubernetes.io/hostname"
    resources:
      limits:
        cpu: "1"
        memory: 1000Mi
      requests:
        cpu: "0.5"
        memory: "500Mi"
