---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster
  namespace: vm-operator
spec:
  # 数据保留时间 h/d/w/y
  retentionPeriod: "1w"
  # 复制因子定义了在不同存储节点之间复制数据的副本数量。
  replicationFactor: 1
  vmstorage:
    logFormat: json
    replicaCount: 2
    # 以 sts 模式运行
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 2G
          storageClassName: nfs-csi-stateful
    storageDataPath: "/vm-data"
    resources:
      limits:
        cpu: "1"
        memory: 1500Mi
  vmselect:
    replicaCount: 2
    cacheMountPath: "/cache"
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 2G
          storageClassName: nfs-csi-stateful
    resources:
      limits:
        cpu: "1"
        memory: "1000Mi"
      requests:
        cpu: "0.5"
        memory: "500Mi"
  vminsert:
    replicaCount: 2
    resources:
      limits:
        cpu: "1"
        memory: 1000Mi
      requests:
        cpu: "0.5"
        memory: "500Mi"