apiVersion: v1
kind: Secret
metadata:
  name: alert-center-external
  namespace: monitoring
stringData:
  alert-config: |-
    - path_prefix: /
      scheme: https
      timeout: 10s
      api_version: v1
      static_configs:
        - targets:
            - alertmanager.k8s.local
