---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: mysqld-metrics
    namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: http
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: mysqld-exporter