apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: mssql-exporter
  name: mssql-exporter-servicemonitor
  namespace: monitoring
spec:
  endpoints:
  - relabelings:
      - sourceLabels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep  # 保留具有 prometheus.io/scrape=true 这个注解的Service
        regex: "true"
      - sourceLabels: [__address__]
        action: replace
        targetLabel: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)  # RE2 正则规则，+是一次到多次，?是0次或1次，其中?:表示非匹配组(意思就是不获取匹配结果)
        replacement: $1:$2
      - sourceLabels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        action: replace
        targetLabel: __scheme__
        regex: (https?)
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
        replacement: $1
      - sourceLabels: [__meta_kubernetes_namespace]
        action: replace
        targetLabel: namespace
      - sourceLabels: [__meta_kubernetes_pod_name]
        action: replace
        targetLabel: pod
      - sourceLabels: [__meta_kubernetes_node_name]
        action: replace
        targetLabel: node
      - sourceLabels: [__meta_kubernetes_pod_container_port_name]
        action: replace
        targetLabel: ID
  jobLabel: mssql-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchExpressions:
      key: app
      operator: In
      values: 
        - mssql-exporter
        - mysqld-exporter
        - postgres-exporter